name: Docker Build/Scan/Push

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-Scan-Push:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}/nix-foundation
      IMAGE_TAG: latest
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      WIZ_POLICY: "nixlab-vuln"
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the latest Docker image
        run: docker build -t ${IMAGE_REPO}:${IMAGE_TAG} .

      - name: Download Wiz CLI
        run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"

      - name: Run Wiz CLI image scan
        id: scan
        run: ./wizcli docker scan -S -i ${IMAGE_REPO}:${IMAGE_TAG} --policy "$WIZ_POLICY" --tag github_action_run_id=${{ github.run_id }}
        continue-on-error: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push the latest Docker image
        run: docker push ${IMAGE_REPO}:${IMAGE_TAG}
